backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: Title }
      - {label: "Tags", name: "tag", widget: "list"}
      - {label: "Categories", name: "categories", widget: "list", default: ["blog"]}
      - {label: "layout", name: "layout", widget: "select", options: ["post", "sharedpost", "draft"]}
      - {label: "postDisclaimmer", name: "layout", widget: "text"}
      - {label: "Thumbnail", name: "thumb", widget: "string"}
      - {label: "Author", name: "author", widget: "string", default: "digvijayb"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Featured Image", name: "img", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}


      
      